# Generated by Django 4.2.21 on 2025-05-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_participant_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='kept_scores',
            field=models.JSONField(default=dict),
        ),
    ]
