# Generated by Django 4.2.21 on 2025-06-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_eventavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventavailability',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('full', 'Fully Booked'), ('blackout', 'Blackout Date')], default='blackout', max_length=10),
        ),
    ]
