# Generated by Django 4.2.21 on 2025-07-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_booking_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Let us know about any special requests, rules, or timings.', null=True),
        ),
    ]
