# Generated by Django 4.2.21 on 2025-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
