# Generated by Django 4.2.21 on 2025-05-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigolfscore',
            name='strokes_by_hole',
            field=models.JSONField(default=dict),
        ),
    ]
