# Generated by Django 4.2.21 on 2025-05-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_minigolfscore_strokes_by_hole'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniGolfScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.minigolfgroup')),
            ],
        ),
    ]
