# Generated by Django 4.2.21 on 2025-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_minigolfscorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigolfscorecard',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
