# Generated by Django 4.2.21 on 2025-05-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_participant_kept_scores'),
        ('events', '0005_minigolfscorecard_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigolfgroup',
            name='scorekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorekept_groups', to='users.participant'),
        ),
    ]
