# Generated by Django 4.2.21 on 2025-05-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_participant_kept_scores'),
        ('events', '0006_alter_minigolfgroup_scorekeeper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletennisconfig',
            name='bonus_for_win_streak',
        ),
        migrations.RemoveField(
            model_name='tabletennisconfig',
            name='matches_to_stay_on',
        ),
        migrations.RemoveField(
            model_name='tabletennisconfig',
            name='max_winstreak_bonus',
        ),
        migrations.RemoveField(
            model_name='tabletennisconfig',
            name='points_per_win',
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='default_points',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='first_place_points',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='fourth_place_points',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='second_place_points',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='target_wins',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='third_place_points',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.CreateModel(
            name='TableTennisPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('has_finished', models.BooleanField(default=False)),
                ('finish_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('queue_position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participant')),
            ],
            options={
                'ordering': ['queue_position'],
            },
        ),
    ]
