# Generated by Django 4.2.21 on 2025-05-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_participant_kept_scores'),
        ('events', '0007_remove_tabletennisconfig_bonus_for_win_streak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolLeaguePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('frames_won', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('finish_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('has_finished', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_league_players', to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PoolLeagueMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_league_matches', to='events.event')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_player1', to='events.poolleagueplayer')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_player2', to='events.poolleagueplayer')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins_as_winner', to='events.poolleagueplayer')),
            ],
        ),
    ]
