# Generated by Django 4.2.21 on 2025-05-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_poolleagueplayer_poolleaguematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolleagueconfig',
            name='points_fifth',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='poolleagueconfig',
            name='points_first',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='poolleagueconfig',
            name='points_fourth',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='poolleagueconfig',
            name='points_second',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='poolleagueconfig',
            name='points_sixth',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='poolleagueconfig',
            name='points_third',
            field=models.IntegerField(default=25),
        ),
    ]
