# Generated by Django 4.2.21 on 2025-05-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_poolleagueconfig_points_fifth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolleagueconfig',
            name='bonus_for_clean_sweep',
        ),
    ]
