# Generated by Django 4.2.21 on 2025-06-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_poolleagueconfig_bonus_for_clean_sweep'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDartsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_first', models.IntegerField(default=50)),
                ('points_second', models.IntegerField(default=35)),
                ('points_third', models.IntegerField(default=25)),
                ('points_fourth', models.IntegerField(default=15)),
                ('points_fifth', models.IntegerField(default=10)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='darts_config', to='events.event')),
            ],
        ),
        migrations.AlterModelOptions(
            name='poolleagueplayer',
            options={'ordering': ['participant__username']},
        ),
        migrations.DeleteModel(
            name='DartsConfig',
        ),
    ]
