# Generated by Django 4.2.21 on 2025-06-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_participant_kept_scores'),
        ('events', '0011_edartsconfig_alter_poolleagueplayer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDartsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darts_groups', to='events.event')),
                ('participants', models.ManyToManyField(to='users.participant')),
            ],
        ),
    ]
