# Generated by Django 4.2.21 on 2025-06-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_participant_kept_scores'),
        ('events', '0012_edartsgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDartsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishing_position', models.PositiveIntegerField()),
                ('points_awarded', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darts_results', to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participant')),
            ],
            options={
                'ordering': ['finishing_position'],
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
