# Generated by Django 4.2.21 on 2025-06-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_edartsresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigolfgroup',
            name='group_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
