# Generated by Django 4.2.21 on 2025-06-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_participant_kept_scores'),
        ('events', '0014_minigolfgroup_group_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Killer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_player_index', models.IntegerField(default=0)),
                ('repeat_shot_pending', models.BooleanField(default=False)),
                ('repeat_shot_forced', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.RenameField(
            model_name='killerconfig',
            old_name='points_per_survivor',
            new_name='points_first',
        ),
        migrations.RemoveField(
            model_name='killerconfig',
            name='bonus_black_pot',
        ),
        migrations.RemoveField(
            model_name='tabletennisconfig',
            name='default_points',
        ),
        migrations.RemoveField(
            model_name='tabletennisconfig',
            name='first_place_points',
        ),
        migrations.RemoveField(
            model_name='tabletennisconfig',
            name='fourth_place_points',
        ),
        migrations.RemoveField(
            model_name='tabletennisconfig',
            name='second_place_points',
        ),
        migrations.RemoveField(
            model_name='tabletennisconfig',
            name='third_place_points',
        ),
        migrations.AddField(
            model_name='killerconfig',
            name='points_fifth',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='killerconfig',
            name='points_fourth',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='killerconfig',
            name='points_second',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='killerconfig',
            name='points_sixth',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='killerconfig',
            name='points_third',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='points_fifth',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='points_first',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='points_fourth',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='points_second',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='points_sixth',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tabletennisconfig',
            name='points_third',
            field=models.IntegerField(default=25),
        ),
        migrations.CreateModel(
            name='KillerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lives', models.IntegerField(default=3)),
                ('turn_order', models.IntegerField()),
                ('eliminated', models.BooleanField(default=False)),
                ('killer_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.killer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participant')),
            ],
        ),
        migrations.AddField(
            model_name='killer',
            name='previous_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='was_previous_player', to='events.killerplayer'),
        ),
    ]
