# Generated by Django 4.2.21 on 2025-06-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_killer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killer',
            name='previous_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='was_previous', to='events.killerplayer'),
        ),
    ]
