# Generated by Django 4.2.21 on 2025-06-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_killer_previous_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='killerconfig',
            name='lives_per_player',
        ),
    ]
