# Generated by Django 4.2.21 on 2025-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_killerplayer_finish_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='killer',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
