# Generated by Django 4.2.21 on 2025-06-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_killer_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='edarts_completed',
            field=models.BooleanField(default=False),
        ),
    ]
