# Generated by Django 4.2.21 on 2025-06-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_edarts_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolleagueplayer',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minigolfconfig',
            name='holes',
            field=models.IntegerField(choices=[(9, '9 Holes'), (18, '18 Holes')], default=18),
        ),
    ]
