# Generated by Django 4.2.21 on 2025-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigolfconfig',
            name='holes',
            field=models.IntegerField(choices=[(18, '18 Holes'), (9, '9 Holes')], default=18),
        ),
    ]
