# Generated by Django 4.2.21 on 2025-06-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_minigolfconfig_holes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigolfconfig',
            name='holes',
            field=models.IntegerField(choices=[(18, '18 Holes')], default=18),
        ),
    ]
