# Generated by Django 4.2.21 on 2025-06-20 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_participant_kept_scores'),
        ('events', '0026_remove_minigolfconfig_overall_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edartsgroup',
            name='scorekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='darts_groups_led', to='users.participant'),
        ),
    ]
