# Generated by Django 4.2.21 on 2025-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_remove_event_edarts_completed_edartsgroup_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigolfconfig',
            name='points_fifth',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='minigolfconfig',
            name='points_fourth',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='minigolfconfig',
            name='points_third',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='poolleagueplayer',
            name='finish_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poolleagueplayer',
            name='points_awarded',
            field=models.FloatField(default=0),
        ),
    ]
